force-app/main/default/objects/Community_Member_Registration_Form__c/Community_Member_Registration_Form__c.object-meta.xml
<CustomObject>
    <description>Stores Registration Details Submitted by Community Members through Vidhaikal  Ngo Site.</description>
    <label>Community Member Registration Form</label>
    <nameField>
        <displayFormat>CMR - {YYYY} - {0000}</displayFormat>
        <label>Community Member Registration Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Member Registraton Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Full street or door number details of the registrant’s residential address.</description>
    <inlineHelpText>Enter Street or area, door number details</inlineHelpText>
    <label>Address Line 1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Obtain Registrant landmark and additional information</description>
    <inlineHelpText>Enter the near landmark</inlineHelpText>
    <label>Address Line 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Annual_Income__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income__c</fullName>
    <description>Income range of the registrant. Used for socio-economic classification and program eligibility.</description>
    <label>Annual Income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Captures admin verification outcome/ default value = ‘Pending’</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City name of the registrant’s residence.</description>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Confirm_Email__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Email__c</fullName>
    <description>Used to verify that the applicant entered the correct email. Should match the Email field through validation.</description>
    <inlineHelpText>Re-Enter Your Email Address exactly as above to confirm</inlineHelpText>
    <label>Confirm Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Registrant country residence</description>
    <inlineHelpText>Select your Country</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
                <default>true</default>
                <label>India</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Primary email address of the registrant. Used for communication, verification, and user account creation.</description>
    <inlineHelpText>Email Should be in format , abc@example.com</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Registrant’s given name. Used for identification and communication.</description>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Registrant’s gender identity. Required for demographic reporting and NGO analytics.</description>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Prefer Not to say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Registrant’s family name or surname. Required to uniquely identify the applicant.</description>
    <label>Last Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Registrant’s mobile phone number. Used for follow-ups and communication.</description>
    <label>Mobile Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <description>Collect the Registrant Occupation to support identiy and background verification</description>
    <label>Occupation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salaried</fullName>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>14</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Proof_of_Identity__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Identity__c</fullName>
    <description>Registrant has to upload valid  proof of identity  for verification purpose</description>
    <inlineHelpText>Select Any one Proof</inlineHelpText>
    <label>Proof of Identity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <description>Used to store the salutation or prefix  (Mr., Ms., Mrs., Dr., others.) provided by the registrant.</description>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State or province where the registrant resides. Captured as a picklist for consistency.</description>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <description>Postal code of the registrant’s address. Helps with geographic categorization and location-based programs.</description>
    <inlineHelpText>Postal / zip code</inlineHelpText>
    <label>Zipcode</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Annual_Income__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income__c</fullName>
    <description>Income range of the registrant. Used for socio-economic classification and program eligibility.</description>
    <label>Annual Income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <description>Collect the Registrant Occupation to support identiy and background verification</description>
    <label>Occupation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salaried</fullName>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Password</label>
    <length>14</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <required>true</required>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/CommunityRegistrationController.cls
/**
* @File Name : CommunityRegistrationController.cls
* @Description :This class is to get the community members Registration details
* @Author :Arthi S
* @Last Modified On : December 11, 2025

*==============================================================================

**/

public with sharing class CommunityRegistrationController {
    
    @AuraEnabled
    
    public static Boolean checkDuplicateEmail(String email) {
        
        if (String.isBlank(email)) return false;
        
        Integer communityCount = [
            SELECT COUNT()
            FROM Community_Member_Registration_Form__c
            WHERE Email__c = :email
        ];
        
        if (communityCount > 0) return true;
        
        Integer contactCount = [
            SELECT COUNT()
            FROM Contact
            WHERE Email = :email
        ];
        
        return contactCount > 0;
    }
    
    @AuraEnabled
    public static Boolean checkDuplicateMobile(String mobileNumber) {
        
        if (String.isBlank(mobileNumber)) return false;
        
        Integer communityCount = [
            SELECT COUNT()
            FROM Community_Member_Registration_Form__c
            WHERE Mobile_Number__c = :mobileNumber
        ];
        
        if (communityCount > 0) return true;
        
        Integer contactCount = [
            SELECT COUNT()
            FROM Contact
            WHERE MobilePhone = :mobileNumber
        ];
        
        return contactCount > 0;
    }
    
    // ---------------- SAVE REGISTRATION + FILE ----------------
    @AuraEnabled
    public static Id saveRegistrationWithFile(
        String salutation,
        String firstName,
        String lastName,
        String mobileNumber,
        String email,
        String confirmEmail,
        String gender,
        String occupation,
        String state,
        String annualIncome,
        String country,
        String city,
        String zipcode,
        String proofOfIdentity,
        String addressLine1,
        String addressLine2,
        String approvalStatus,
        String password,
        String fileName,
        String base64Data,
        String contentType
    ){
        
        if (checkDuplicateEmail(email)) {
            throw new AuraHandledException('EMAIL_DUPLICATE');
        }
        
        if (checkDuplicateMobile(mobileNumber)) {
            throw new AuraHandledException('MOBILE_DUPLICATE');
        }
        
        
        if (String.isBlank(fileName) || String.isBlank(base64Data)) {
            throw new AuraHandledException('ID Proof upload is mandatory.');
        }
        // Normalize jpeg → jpg (Salesforce-safe workaround)
        if (fileName.toLowerCase().endsWith('.jpeg')) {
            fileName = fileName.replaceAll('(?i)\\.jpeg$', '.jpg');
        }
        
        // Allow only safe extensions
        String lowerName = fileName.toLowerCase();
        if (
            !lowerName.endsWith('.pdf') &&
            !lowerName.endsWith('.jpg') &&
            !lowerName.endsWith('.png')
        ) {
            throw new AuraHandledException(
                'Only PDF, JPG, JPEG, and PNG files are allowed.'
            );
        }
        
        Integer MAX_SIZE = 5 * 1024 * 1024; // 5MB
        Blob fileBlob = EncodingUtil.base64Decode(base64Data);
        
        if (fileBlob.size() > MAX_SIZE) {
            throw new AuraHandledException(fileName + ' exceeds the 5MB file size limit.');
        }
        
        // --- Create Registration Record ---
        
        Community_Member_Registration_Form__c reg = new Community_Member_Registration_Form__c();
        try{
            reg.Salutation__c = salutation;
            reg.First_Name__c = firstName;
            reg.Last_Name__c = lastName;
            reg.Mobile_Number__c = mobileNumber;
            reg.Email__c = email;
            reg.Confirm_Email__c = confirmEmail;
            reg.Gender__c = gender;
            reg.Occupation__c = occupation;
            reg.State__c = state;
            if (!String.isBlank(annualIncome)) {
                reg.Annual_Income__c = Decimal.valueOf(annualIncome.trim());
            }
            
            //reg.Annual_Income__c = Decimal.valueOf(annualIncome);
            reg.Country__c = country;
            reg.City__c = city;
            
            
            reg.Zipcode__c = Integer.valueOf(zipcode);
            
            reg.Proof_of_Identity__c = proofOfIdentity;
            reg.Address_Line_1__c = addressLine1;
            reg.Address_Line_2__c = addressLine2;
            reg.Approval_Status__c = approvalStatus;
            reg.Password__c= password;
            
            insert reg;
        } catch (Exception e) {
            System.debug('ERROR: ' + e.getMessage());
            throw new AuraHandledException('Registration failed: ' + e.getMessage());
        }
        
        // --- Save File ---
        ContentVersion cv = new ContentVersion();
        cv.Title = fileName;
        cv.PathOnClient = fileName;
        cv.VersionData = fileBlob;
        cv.FirstPublishLocationId = reg.Id; // Link to registration record
        insert cv;
        
        return reg.Id;
    }
}