force-app/main/default/objects/Community_Member_Registration_Form__c/Community_Member_Registration_Form__c.object-meta.xml
<CustomObject>
    <description>Stores Registration Details Submitted by Community Members through Vidhaikal  Ngo Site.</description>
    <label>Community Member Registration Form</label>
    <nameField>
        <displayFormat>CMR - {YYYY} - {0000}</displayFormat>
        <label>Community Member Registration Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Member Registraton Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Full street or door number details of the registrant’s residential address.</description>
    <inlineHelpText>Enter Street or area, door number details</inlineHelpText>
    <label>Address Line 1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Obtain Registrant landmark and additional information</description>
    <inlineHelpText>Enter the near landmark</inlineHelpText>
    <label>Address Line 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Annual_Income__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income__c</fullName>
    <description>Income range of the registrant. Used for socio-economic classification and program eligibility.</description>
    <label>Annual Income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City name of the registrant’s residence.</description>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Registrant country residence</description>
    <inlineHelpText>Select your Country</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
                <default>true</default>
                <label>India</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Primary email address of the registrant. Used for communication, verification, and user account creation.</description>
    <inlineHelpText>Email Should be in format , abc@example.com</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Registrant’s given name. Used for identification and communication.</description>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Registrant’s gender identity. Required for demographic reporting and NGO analytics.</description>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Prefer Not to say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Registrant’s family name or surname. Required to uniquely identify the applicant.</description>
    <label>Last Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Registrant’s mobile phone number. Used for follow-ups and communication.</description>
    <label>Mobile Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <description>Collect the Registrant Occupation to support identiy and background verification</description>
    <label>Occupation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salaried</fullName>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <description>Used to store the salutation or prefix  (Mr., Ms., Mrs., Dr., others.) provided by the registrant.</description>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Ms.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State or province where the registrant resides. Captured as a picklist for consistency.</description>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Zipcode__c.field-meta.xml
<CustomField>
    <fullName>Zipcode__c</fullName>
    <description>Postal code of the registrant’s address. Helps with geographic categorization and location-based programs.</description>
    <inlineHelpText>Postal / zip code</inlineHelpText>
    <label>Zipcode</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Annual_Income__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income__c</fullName>
    <description>Income range of the registrant. Used for socio-economic classification and program eligibility.</description>
    <label>Annual Income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <description>Collect the Registrant Occupation to support identiy and background verification</description>
    <label>Occupation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salaried</fullName>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Community_Member.recordType-meta.xml
<RecordType>
    <fullName>Community_Member</fullName>
    <active>true</active>
    <description>Details of Approved Community Memer data</description>
    <label>Community Member</label>
</RecordType>

force-app/main/default/classes/CommunityMemberConversionService.cls
public with sharing class CommunityMemberConversionService {

    @AuraEnabled
    public static Id convertRegistrationToContact(Id registrationId) {

        System.debug('### START convertRegistrationToContact ###');
        System.debug('Registration Id received: ' + registrationId);

        // Fetch Registration record
       Community_Member_Registration_Form__c reg = [
            SELECT Id, Salutation__c, First_Name__c, Last_Name__c, Email__c,
                   Mobile_Number__c, Gender__c, Occupation__c, Annual_Income__c,
                   State__c, Address_Line_1__c, Address_Line_2__c,
                   City__c, Zipcode__c,Country__c
            FROM Community_Member_Registration_Form__c
            WHERE Id = :registrationId
            LIMIT 1
        ];

        System.debug('Fetched Registration Record: ' + reg);

        // Get Contact Record Type
        List<RecordType> rtList = [
            SELECT Id
            FROM RecordType
            WHERE SObjectType = 'Contact'
            AND DeveloperName = 'Community_Member'
            LIMIT 1
        ];

        if (rtList.isEmpty()) {
            System.debug('Contact RecordType Community_Member not found');
            throw new AuraHandledException('Contact Record Type not found');
        }

        Id contactRtId = rtList[0].Id;
        System.debug('Community Member Contact RecordType Id: ' + contactRtId);

        
        //  Create Contact
        Contact con = new Contact();

        // Basic Info
        con.Salutation   = reg.Salutation__c;
        con.FirstName    = reg.First_Name__c;
        con.LastName     = String.isBlank(reg.Last_Name__c)
                           ? 'Community Member'
                           : reg.Last_Name__c;
        con.Email        = reg.Email__c;
        con.MobilePhone  = reg.Mobile_Number__c;

        // Custom Fields
        con.GenderIdentity     = reg.Gender__c;
        con.Occupation__c     = reg.Occupation__c;
        con.Annual_Income__c  = reg.Annual_Income__c;

        // Address
        con.MailingStreet =
            reg.Address_Line_1__c +
            (String.isNotBlank(reg.Address_Line_2__c)
                ? ', ' + reg.Address_Line_2__c
                : '');

        con.MailingCity       = reg.City__c;
        con.MailingState      = reg.State__c;
        con.MailingPostalCode = String.valueOf(reg.Zipcode__c);
        con.MailingCountry = reg.Country__c;
        con.RecordTypeId = contactRtId;
	    System.debug('Contact before insert: ' + con);
        insert con;
        System.debug('Contact successfully created. Contact Id: ' + con.Id);      
        return con.Id;
    }
}