force-app/main/default/objects/Community_Member_Registration_Form__c/Community_Member_Registration_Form__c.object-meta.xml
<CustomObject>
    <description>Stores Registration Details Submitted by Community Members through Vidhaikal  Ngo Site.</description>
    <label>Community Member Registration Form</label>
    <nameField>
        <displayFormat>CMR - {YYYY} - {0000}</displayFormat>
        <label>Community Member Registration Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Member Registraton Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Captures admin verification outcome/ default value = ‘Pending’</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Primary email address of the registrant. Used for communication, verification, and user account creation.</description>
    <inlineHelpText>Email Should be in format , abc@example.com</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/CheckMemberStatusController.cls
/**
* @File Name : CheckMemberStatusController .cls
* @Description :This class is create to check the member status by email
* @Author :Neelima
* @Last Modified On : December 5, 2025

*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | December 5, 2025 |   | Initial Version
**/

public with sharing class CheckMemberStatusController {

    @AuraEnabled(cacheable=true)
    public static string  isEmailRegistered(String email) {
        if (String.isBlank(email)) {
            return 'EMPTY';
        }
       
        List<Community_Member_Registration_Form__c> found = [
            SELECT Id,Approval_Status__c    
            FROM Community_Member_Registration_Form__c 
            WHERE Email__c = :email
            LIMIT 1

        ];
		if(found.isEmpty()){
			return 'Not_Found';
		}
        return found[0].Approval_Status__c;
    }
}