force-app/main/default/objects/Community_Member_Registration_Form__c/Community_Member_Registration_Form__c.object-meta.xml
<CustomObject>
    <description>Stores Registration Details Submitted by Community Members through Vidhaikal  Ngo Site.</description>
    <label>Community Member Registration Form</label>
    <nameField>
        <displayFormat>CMR - {YYYY} - {0000}</displayFormat>
        <label>Community Member Registration Form Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Community Member Registraton Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <description>Full street or door number details of the registrant’s residential address.</description>
    <inlineHelpText>Enter Street or area, door number details</inlineHelpText>
    <label>Address Line 1</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <description>Obtain Registrant landmark and additional information</description>
    <inlineHelpText>Enter the near landmark</inlineHelpText>
    <label>Address Line 2</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Annual_Income__c.field-meta.xml
<CustomField>
    <fullName>Annual_Income__c</fullName>
    <description>Income range of the registrant. Used for socio-economic classification and program eligibility.</description>
    <label>Annual Income</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>Approval_Status__c</fullName>
    <description>Captures admin verification outcome/ default value = ‘Pending’</description>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <description>City name of the registrant’s residence.</description>
    <label>City</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Confirm_Email__c.field-meta.xml
<CustomField>
    <fullName>Confirm_Email__c</fullName>
    <description>Used to verify that the applicant entered the correct email. Should match the Email field through validation.</description>
    <inlineHelpText>Re-Enter Your Email Address exactly as above to confirm</inlineHelpText>
    <label>Confirm Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>Registrant country residence</description>
    <inlineHelpText>Select your Country</inlineHelpText>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
                <default>true</default>
                <label>India</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>Primary email address of the registrant. Used for communication, verification, and user account creation.</description>
    <inlineHelpText>Email Should be in format , abc@example.com</inlineHelpText>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <description>Registrant’s given name. Used for identification and communication.</description>
    <label>First Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <description>Registrant’s gender identity. Required for demographic reporting and NGO analytics.</description>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Prefer Not to say</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <description>Registrant’s family name or surname. Required to uniquely identify the applicant.</description>
    <label>Last Name</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Mobile_Number__c.field-meta.xml
<CustomField>
    <fullName>Mobile_Number__c</fullName>
    <description>Registrant’s mobile phone number. Used for follow-ups and communication.</description>
    <label>Mobile Number</label>
    <required>true</required>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Occupation__c.field-meta.xml
<CustomField>
    <fullName>Occupation__c</fullName>
    <description>Collect the Registrant Occupation to support identiy and background verification</description>
    <label>Occupation</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salaried</fullName>
            </value>
            <value>
                <fullName>Self-Employed</fullName>
            </value>
            <value>
                <fullName>Student</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/Proof_of_Identity__c.field-meta.xml
<CustomField>
    <fullName>Proof_of_Identity__c</fullName>
    <description>Registrant has to upload valid  proof of identity  for verification purpose</description>
    <inlineHelpText>Select Any one Proof</inlineHelpText>
    <label>Proof of Identity</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aadhar</fullName>
            </value>
            <value>
                <fullName>Driving License</fullName>
            </value>
            <value>
                <fullName>PAN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Community_Member_Registration_Form__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <description>State or province where the registrant resides. Captured as a picklist for consistency.</description>
    <label>State</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Andhra Pradesh</fullName>
            </value>
            <value>
                <fullName>Arunachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Assam</fullName>
            </value>
            <value>
                <fullName>Bihar</fullName>
            </value>
            <value>
                <fullName>Chhattisgarh</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Goa</fullName>
            </value>
            <value>
                <fullName>Gujarat</fullName>
            </value>
            <value>
                <fullName>Haryana</fullName>
            </value>
            <value>
                <fullName>Himachal Pradesh</fullName>
            </value>
            <value>
                <fullName>Jharkhand</fullName>
            </value>
            <value>
                <fullName>Karnataka</fullName>
            </value>
            <value>
                <fullName>Kerala</fullName>
            </value>
            <value>
                <fullName>Madhya Pradesh</fullName>
            </value>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Manipur</fullName>
            </value>
            <value>
                <fullName>Meghalaya</fullName>
            </value>
            <value>
                <fullName>Mizoram</fullName>
            </value>
            <value>
                <fullName>Nagaland</fullName>
            </value>
            <value>
                <fullName>Odisha</fullName>
            </value>
            <value>
                <fullName>Punjab</fullName>
            </value>
            <value>
                <fullName>Rajasthan</fullName>
            </value>
            <value>
                <fullName>Sikkim</fullName>
            </value>
            <value>
                <fullName>Tamil Nadu</fullName>
            </value>
            <value>
                <fullName>Telangana</fullName>
            </value>
            <value>
                <fullName>Tripura</fullName>
            </value>
            <value>
                <fullName>Uttarakhand</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RegistrationControllerTest.cls
@isTest
public class RegistrationControllerTest {
    @testSetup
    public static void setupTestData() {
        Community_Member_Registration_Form__c reg = new Community_Member_Registration_Form__c(
            First_Name__c = 'Arthi',
            Last_Name__c = 'S',
            Email__c = '@gmail.com',
            Confirm_Email__c = 'test@gmail.com',
            Mobile_Number__c = '9999999999',
            Gender__c = 'Female',
            Occupation__c = 'Engineer',
            Address_Line_1__c = 'Street 1',
            Address_Line_2__c = 'Street 2',
            State__c = 'TN',
            Country__c = 'India',
            City__c = 'Chennai',
            Proof_of_Identity__c = 'AADHAR',
            Annual_Income__c=decimal.valueof('100000'),
            Approval_Status__c='Pending'
        );
        insert reg;
    }
    

}